### ISSUE TITLE
Integrate Google Maps

### ISSUE THREAD

**Issue by epartakki** [epartakki/valetbike#31]

**Comment by epartakki** [comment]
Customize marker icons, search for places

https://developers.google.com/maps/documentation/javascript/adding-a-google-map#maps_add_map-javascript

**Comment by epartakki** [comment]
Optional libraries when you load the Maps JS API to add extended functionality: Places library

**Comment by sunniraleigh** [comment]
https://developers.google.com/maps/documentation/directions
